version: 2
jobs:
  build:
    docker:
      - image: microsoft/dotnet:2.2-sdk-alpine
    steps:
      - checkout
      - run: dotnet restore
      - run: dotnet build
      - run: dotnet test --no-build tests/AdventOfCode.Tests/AdventOfCode.Tests.csproj
